### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by serin-delaunay** [Wangscape/Wangscape#92]
I was sure I put an MIT license on Wangscape, but I can't find any record of it, either here or in Wangview. Very strange. A license should be added to both before [Release 0.1](https://github.com/Wangscape/Wangscape/milestone/1).

I would prefer either MIT or Apache; @hryniuk, do you have a preference?

**Comment by hryniuk** [comment]
For me _GPL_ has been the best since I rember (e.g. [The Importance of Contracts](http://zguide.zeromq.org/page:all#The-Importance-of-Contracts) and [Eat Me](http://zguide.zeromq.org/page:all#Eat-Me) from "ØMQ - The Guide" has some arguments for it), but if you'd like to choose between MIT and Apache, I think **MIT** is more appropiate here, because of:
* we don't care about any patents connected to Wangscape (I belive :wink:)
* it's lighter, more approachable and, as I've noticed, more popular
* for me it's a real success, when people play with your code, change it and adjust it to their needs, **MIT** makes it easier (don't force them to register changes as Apache does - https://choosealicense.com/licenses/).

**Comment by serin-delaunay** [comment]
I'm not willing to use GPL ;) so let's go with MIT.
